server.port=8080

springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.displayRequestDuration=true
springdoc.packages-to-scan=com.mtg.magicApi.card.controller